title: Semantic Docstrings
description: A semantic documentation standard for Python that captures Responsibility, Context, Role, and Boundaries.
author: "Davi Guides"

theme: minima
remote_theme: "jekyll/minima@1e8a445"

baseurl: "/semantic-docstrings"
repository: daviguides/semantic-docstrings

# Minima social links
github_username: daviguides
linkedin_username: daviguides


markdown: kramdown
kramdown:
  input: GFM
