title: Semantic Docstrings
description: A semantic documentation standard for Python that captures Responsibility, Context, Role, and Boundaries.
author: "Davi Guides"

theme: minima

# baseurl: "/semantic-docstrings"
repository: daviguides/semantic-docstrings

# Minima social links
github_username: daviguides
linkedin_username: daviguides

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  skin: solarized-light
  date_format: "%Y-%m-%d"

markdown: kramdown
kramdown:
  input: GFM
