title: Semantic Docstrings
description: A semantic documentation standard for Python that captures Responsibility, Context, Role, and Boundaries.
author: "Davi Guides"

theme: minima

baseurl: "/semantic-docstrings"
repository: daviguides/semantic-docstrings

# Minima social links
github_username: daviguides
linkedin_username: daviguides

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  skin: solarized-light
  date_format: "%Y-%m-%d"

include:
    - _pages

header_pages:
  - index.md
  - _pages/why_semantic_docstrings.md
  - _pages/semantic_docstrings.md

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

markdown: kramdown
kramdown:
  input: GFM
