title: Semantic Docstrings
description: A semantic documentation standard for Python that captures Responsibility, Context, Role, and Boundaries.
theme: minima
remote_theme: "jekyll/minima@1e8a445"
baseurl: ""
url: ""
markdown: kramdown
kramdown:
  input: GFM
